### ISSUE TITLE
Book 5 Section 288

### ISSUE THREAD

**Issue by aggsol** [tonib/kaichronicles#14]
Error: Cannot move to section 399

The section reads: *If you have ever been given a Crystal Star Pendant* it is possible to have met Banedon in Book 1 but the player may have lost the pendant (no long in the backpack). As at least Banedon recognizes Lone Wolf while not having the pendant is anymore should still lead to section 399.

**Comment by tonib** [comment]
Fixed on book 2 (sect328) and book 5 (sect221, sect288 and sect382), thank you
