### ISSUE TITLE
Book 6 sections 132 and 148

### ISSUE THREAD

**Issue by Baljak** [tonib/kaichronicles#19]
These are the two sections where you can buy Altan's horse. The checks for the special items or the money don't work. Even if you have 2 special items or 20 gold crowns, you can't go to section 212.

**Comment by tonib** [comment]
Hello, it seems to work. Maybe it's not well explained. There is a message saying: "If you agree to his proposal, drop 2 Special Items or 20 Gold Crowns". If you drop 2 Special Items OR 20 Gold Crowns, you can go to the section 212. 
[2018_09_03_19_45_06-book-6-savegame.json.zip](https://github.com/tonib/kaichronicles/files/2346312/2018_09_03_19_45_06-book-6-savegame.json.zip)

Attached save game with section 148. You can play it at https://projectaon.org/staff/toni/ > load game (unzip it first)

**Comment by Baljak** [comment]
Indeed I didn't get it was needed to drop items to activate the links.
